language: java
addons:
  sonarcloud:
    organization: "ann-cher-github" # the key of the org you chose at step #3
    token:
      secure: 0bc2ef85fa2182bfe1ffc4becaba5fae8453134a
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
